server:
  port: 8085
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    url: ${DB_CONNECTION_URL:jdbc:h2:mem:GRAFFITI_BOARD;MODE=MSSQLServer}
    driver-class-name: ${DB_DRIVER_CLASSNAME:org.h2.Driver}
  flyway:
    locations: classpath:db/migration/sqlserver
    enabled: true
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
      path-mapping:
        health: healthz
    enabled-by-default: false
dfs:
  board:
    security:
      users:
        - name: John
          password: Doe
        - name: Max
          password: Mustermann
